import { BookOpen, GitFork, HardDrive, HelpCircle, Search, ShieldCheck } from 'lucide-react'
import { useWorkspace } from '../context/WorkspaceContext'

export function HelpPage() {
  const { clearWorkspace } = useWorkspace()
  return <div className="page-container help-page">
    <section className="page-heading"><div className="eyebrow"><HelpCircle size={14} /> Guide</div><h1>How to use Lexigraph</h1><p>From an ambiguous word to a precise, editable model of an idea.</p></section>
    <div className="help-layout"><nav><a href="#senses">1. Collect senses</a><a href="#graphs">2. Compose concepts</a><a href="#articles">3. Map an article</a><a href="#storage">4. Your data</a></nav><div className="help-content">
      <section id="senses"><div className="help-icon"><Search /></div><div><span>STEP ONE</span><h2>Collect exact meanings</h2><p>Open <strong>Sense lab</strong> and begin typing. You can only choose words present in WordNet. Select the intended sense using its definition and example sentence. Each synset receives a stable ID based on its WordNet offset; each word inside it receives its own ID.</p><div className="callout">Hover a collected sense at any time to see its definition again.</div></div></section>
      <section id="graphs"><div className="help-icon"><GitFork /></div><div><span>STEP TWO</span><h2>Compose higher-order concepts</h2><p>Open <strong>Concept graph</strong>. Click a palette item to place it and drag nodes freely. To create a relationship, drag from the right handle to the left handle, or choose its source and target in <strong>Create a link</strong>. Choose a WordNet sense as semantic glue. Use the relation’s <strong>Edit</strong> action (or double-click the edge) to change its meaning or delete it, drag an endpoint to reconnect it, or select a node or edge and press Delete to remove it.</p></div></section>
      <section id="articles"><div className="help-icon"><BookOpen /></div><div><span>STEP THREE</span><h2>Decode an article</h2><p>Paste an English Wikipedia URL or select a suggested scientific topic. Highlight any word or phrase in the article, then map the passage to a precise WordNet sense. Mapped meanings join your palette, ready for one or several graphs.</p></div></section>
      <section id="storage"><div className="help-icon"><HardDrive /></div><div><span>LOCAL FIRST</span><h2>Your work stays with you</h2><p>Every sense, graph position, relationship, and article annotation is immediately stored in an account-specific browser cache. When online, PocketBase events update every open device in real time. When offline, edits remain queued locally and are merged automatically on reconnection—even when several devices changed different parts of the workspace.</p><div className="privacy"><ShieldCheck /><span><strong>Private by default.</strong><br />Authentication requires a verified email, whether you use a password or GitHub. If you forget a password, use <strong>Forgot password?</strong> on the sign-in page. PocketBase rules restrict both snapshots and the CRDT operation journal to their owner; the header cloud icon shows whether changes are live, merging, or queued offline.</span></div><button className="danger-button" onClick={() => window.confirm('Erase the entire Lexigraph workspace locally and in PocketBase?') && clearWorkspace()}>Reset workspace</button></div></section>
    </div></div>
  </div>
}
