import { BookOpen, GitFork, HardDrive, HelpCircle, Search, ShieldCheck } from 'lucide-react'
import { useWorkspace } from '../context/WorkspaceContext'

export function HelpPage() {
  const { clearWorkspace } = useWorkspace()
  return <div className="page-container help-page">
    <section className="page-heading"><div className="eyebrow"><HelpCircle size={14} /> Guide</div><h1>How to use Lexigraph</h1><p>From an ambiguous word to a precise, editable model of an idea.</p></section>
    <div className="help-layout"><nav><a href="#senses">1. Collect senses</a><a href="#graphs">2. Compose concepts</a><a href="#articles">3. Map an article</a><a href="#storage">4. Your data</a></nav><div className="help-content">
      <section id="senses"><div className="help-icon"><Search /></div><div><span>STEP ONE</span><h2>Collect exact meanings</h2><p>Open <strong>Sense lab</strong> and begin typing. You can only choose words present in WordNet. Select the intended sense using its definition and example sentence. Each synset receives a stable ID based on its WordNet offset; each word inside it receives its own ID.</p><div className="callout">Hover a collected sense at any time to see its definition again.</div></div></section>
      <section id="graphs"><div className="help-icon"><GitFork /></div><div><span>STEP TWO</span><h2>Compose higher-order concepts</h2><p>Open <strong>Concept graph</strong>. Use <strong>Canvas</strong> to place and drag entities visually, or <strong>Columns</strong> to edit the same model as Source / Relationship / Target statements. Create a relationship by dragging between handles or choosing its endpoints in the sidebar, then select a WordNet sense as semantic glue. The minimap at lower right previews all entities and lets you orient the canvas. Edit an entity to replace its sense without losing its links, or delete it together with its incident relationships. Every destructive action asks for confirmation.</p><div className="callout"><strong>Quick add:</strong> enter <code>system#1</code> for an entity, or <code>cause#1 → produce#2 → effect#1</code> for entities plus a relationship. The number intentionally selects the WordNet sense.</div></div></section>
      <section id="articles"><div className="help-icon"><BookOpen /></div><div><span>STEP THREE</span><h2>Decode an article</h2><p>Paste an English Wikipedia URL or select a suggested scientific topic. Highlight any word or phrase in the article, then map the passage to a precise WordNet sense. Mapped meanings join your palette, ready for one or several graphs.</p><div className="callout"><strong>Quick map passages:</strong> paste one mapping per line as <code>exact passage | system#1</code>. Each passage must occur in the article and the number selects a WordNet sense.</div></div></section>
      <section id="storage"><div className="help-icon"><HardDrive /></div><div><span>LOCAL FIRST</span><h2>Your work stays with you</h2><p>Every sense, graph position, relationship, and article annotation is immediately stored as an Automerge document in account-specific browser IndexedDB. When online, PocketBase events update every open device in real time. When offline, binary changes remain queued locally and Automerge merges them automatically on reconnection—even when several devices edited the workspace concurrently. Periodic checkpoints keep cloud replay compact without discarding concurrent changes.</p><p>You may also choose <strong>Use this device only</strong> from the sign-in screen. It skips login and PocketBase entirely, storing the workspace only in this browser’s local storage. It is private and works from GitHub Pages, but has no backup or cross-device sync: clearing site data removes it.</p><div className="privacy"><ShieldCheck /><span><strong>Private by default.</strong><br />Authentication requires a verified email only for cloud sync, whether you use a password or GitHub. If you forget a password, use <strong>Forgot password?</strong> on the sign-in page. PocketBase rules restrict changes and checkpoints to their owner; the header cloud icon shows whether changes are live, merging, queued offline, or local-only.</span></div><button className="danger-button" onClick={() => window.confirm('Reset this Lexigraph workspace? Local-only work cannot be recovered once browser data is cleared.') && clearWorkspace()}>Reset workspace</button></div></section>
    </div></div>
  </div>
}
